import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const categories = [
  {
    id: 'cat-revestimientos-plasticos',
    name: 'Revestimientos Plásticos',
    slug: 'revestimientos-plasticos',
    description: 'Revestimientos plásticos de alta calidad para interiors y exteriores. Acabado resistente y duradero.',
    image: '/products/revestimiento-plastico.jpg',
    order: 1,
  },
  {
    id: 'cat-revestimientos-texturados',
    name: 'Revestimientos Texturados',
    slug: 'revestimientos-texturados',
    description: 'Revestimientos con texturas decorativas que aportan personalidad y estilo a tus paredes.',
    image: '/products/revestimiento-texturado.jpg',
    order: 2,
  },
  {
    id: 'cat-revestimientos-al-agua',
    name: 'Revestimientos al Agua',
    slug: 'revestimientos-al-agua',
    description: 'Revestimientos al agua ecológicos, de fácil aplicación y bajo olor. Ideales para ambientes cerrados.',
    image: '/products/revestimiento-agua.jpg',
    order: 3,
  },
  {
    id: 'cat-enduidos',
    name: 'Enduidos y Preparación',
    slug: 'enduidos',
    description: 'Enduidos y productos de preparación de superficies para un acabado perfecto antes de pintar.',
    image: '/products/enduido.jpg',
    order: 4,
  },
  {
    id: 'cat-pinturas',
    name: 'Pinturas',
    slug: 'pinturas',
    description: 'Pinturas de primera calidad para interiores y exteriores con amplia gama de colores.',
    image: '/products/pintura.jpg',
    order: 5,
  },
  {
    id: 'cat-accesorios',
    name: 'Accesorios y Herramientas',
    slug: 'accesorios',
    description: 'Rodillos, espátulas, bandejas y todo lo necesario para una aplicación profesional.',
    image: '/products/accesorios.jpg',
    order: 6,
  },
];

const products = [
  // Revestimientos Plásticos
  {
    id: 'prod-lecatex-plastico-20',
    name: 'Lecatex Plástico Clásico 20L',
    slug: 'lecatex-plastico-clasico-20l',
    description: 'Revestimiento plástico de alta cobertura para exteriores. Resistente a la intemperie, lavable y de larga duración. Aplicación con rodillo o espátula. Acabado rústico elegante que disimula imperfecciones de la superficie.',
    price: 45900,
    comparePrice: 52000,
    unit: 'balde 20L',
    weight: 22,
    image: '/products/lecatex-plastico-20.jpg',
    images: '[]',
    category: 'Revestimientos Plásticos',
    categorySlug: 'revestimientos-plasticos',
    featured: true,
    inStock: true,
    stockQty: 50,
    colors: '["Blanco","Beige","Gris claro","Terracota"]',
    sizes: '["4L","10L","20L"]',
  },
  {
    id: 'prod-lecatex-plastico-10',
    name: 'Lecatex Plástico Clásico 10L',
    slug: 'lecatex-plastico-clasico-10l',
    description: 'Revestimiento plástico versátil para interiores y exteriores. Excelente cobertura y adherencia. Secado rápido y fácil de aplicar. Disponible en variedad de colores.',
    price: 24900,
    comparePrice: 28000,
    unit: 'balde 10L',
    weight: 11,
    image: '/products/lecatex-plastico-10.jpg',
    images: '[]',
    category: 'Revestimientos Plásticos',
    categorySlug: 'revestimientos-plasticos',
    featured: false,
    inStock: true,
    stockQty: 80,
    colors: '["Blanco","Beige","Gris claro","Terracota"]',
    sizes: '["4L","10L","20L"]',
  },
  {
    id: 'prod-lecatex-plastico-4',
    name: 'Lecatex Plástico Clásico 4L',
    slug: 'lecatex-plastico-clasico-4l',
    description: 'Revestimiento plástico en presentación chica ideal para refacciones o detalles. Misma calidad y resistencia que la línea completa en un formato práctico.',
    price: 12900,
    comparePrice: null,
    unit: 'balde 4L',
    weight: 4.5,
    image: '/products/lecatex-plastico-4.jpg',
    images: '[]',
    category: 'Revestimientos Plásticos',
    categorySlug: 'revestimientos-plasticos',
    featured: false,
    inStock: true,
    stockQty: 120,
    colors: '["Blanco","Beige","Gris claro"]',
    sizes: '["4L"]',
  },
  // Revestimientos Texturados
  {
    id: 'prod-lecatex-rustico-20',
    name: 'Lecatex Rústico Texturado 20L',
    slug: 'lecatex-rustico-texturado-20l',
    description: 'Revestimiento texturado de efecto rústico para exteriores. Crea una superficie con relieve y profundidad. Resistente a la intemperie y los rayos UV. Ideal para fachadas y frentes.',
    price: 52900,
    comparePrice: 58000,
    unit: 'balde 20L',
    weight: 23,
    image: '/products/lecatex-rustico-20.jpg',
    images: '[]',
    category: 'Revestimientos Texturados',
    categorySlug: 'revestimientos-texturados',
    featured: true,
    inStock: true,
    stockQty: 40,
    colors: '["Blanco","Beige","Terracota","Piedra","Arena"]',
    sizes: '["10L","20L"]',
  },
  {
    id: 'prod-lecatex-salteado-10',
    name: 'Lecatex Salteado Decorativo 10L',
    slug: 'lecatex-salteado-decorativo-10l',
    description: 'Revestimiento decorativo de efecto salteado que aporta movimiento y textura a tus paredes. Fácil aplicación con espátula o pincel. Resultado profesional garantizado.',
    price: 31900,
    comparePrice: null,
    unit: 'balde 10L',
    weight: 12,
    image: '/products/lecatex-salteado-10.jpg',
    images: '[]',
    category: 'Revestimientos Texturados',
    categorySlug: 'revestimientos-texturados',
    featured: false,
    inStock: true,
    stockQty: 60,
    colors: '["Blanco","Crema","Gris","Terracota"]',
    sizes: '["4L","10L"]',
  },
  {
    id: 'prod-lecatex-gotalete-20',
    name: 'Lecatex Gotaleta 20L',
    slug: 'lecatex-gotaleta-20l',
    description: 'Revestimiento con efecto gotaleta para un acabado sofisticado y duradero. Textura fina que combina elegancia y resistencia. Perfecto para ambientes de alto tránsito.',
    price: 49900,
    comparePrice: null,
    unit: 'balde 20L',
    weight: 22,
    image: '/products/lecatex-gotalete-20.jpg',
    images: '[]',
    category: 'Revestimientos Texturados',
    categorySlug: 'revestimientos-texturados',
    featured: true,
    inStock: true,
    stockQty: 35,
    colors: '["Blanco","Beige","Gris perla"]',
    sizes: '["10L","20L"]',
  },
  // Revestimientos al Agua
  {
    id: 'prod-lecatex-agua-20',
    name: 'Lecatex al Agua Premium 20L',
    slug: 'lecatex-agua-premium-20l',
    description: 'Revestimiento al agua de última generación. Bajo olor, ecológico y de secado rápido. Ideal para interiores y espacios ventilados. Lavable y resistente al frote.',
    price: 38900,
    comparePrice: 43000,
    unit: 'balde 20L',
    weight: 21,
    image: '/products/lecatex-agua-20.jpg',
    images: '[]',
    category: 'Revestimientos al Agua',
    categorySlug: 'revestimientos-al-agua',
    featured: true,
    inStock: true,
    stockQty: 55,
    colors: '["Blanco","Beige","Gris claro","Rosa pálido","Celeste"]',
    sizes: '["4L","10L","20L"]',
  },
  {
    id: 'prod-lecatex-agua-10',
    name: 'Lecatex al Agua Classic 10L',
    slug: 'lecatex-agua-classic-10l',
    description: 'Revestimiento al agua de excelente rendimiento y cobertura. Fácil de aplicar y limpiar. Apto para ambientes con niños y mascotas por su fórmula libre de solventes.',
    price: 21900,
    comparePrice: null,
    unit: 'balde 10L',
    weight: 11,
    image: '/products/lecatex-agua-10.jpg',
    images: '[]',
    category: 'Revestimientos al Agua',
    categorySlug: 'revestimientos-al-agua',
    featured: false,
    inStock: true,
    stockQty: 90,
    colors: '["Blanco","Beige","Gris claro"]',
    sizes: '["4L","10L"]',
  },
  // Enduidos
  {
    id: 'prod-lecatex-enduido-10',
    name: 'Lecatex Enduido Interior 10L',
    slug: 'lecatex-enduido-interior-10l',
    description: 'Enduido de alta calidad para preparación de superficies interiores. Rellena imperfecciones y deja una base lisa y perfecta para pintar. Secado rápido y fácil lijado.',
    price: 18900,
    comparePrice: null,
    unit: 'balde 10L',
    weight: 12,
    image: '/products/lecatex-enduido-10.jpg',
    images: '[]',
    category: 'Enduidos y Preparación',
    categorySlug: 'enduidos',
    featured: false,
    inStock: true,
    stockQty: 70,
    colors: '["Blanco"]',
    sizes: '["4L","10L","20L"]',
  },
  {
    id: 'prod-lecatex-enduido-ext-20',
    name: 'Lecatex Enduido Exterior 20L',
    slug: 'lecatex-enduido-exterior-20l',
    description: 'Enduido especial para exteriores con resistencia a la humedad y la intemperie. Prepara superficies exteriores para recibir revestimientos o pinturas de larga duración.',
    price: 34900,
    comparePrice: null,
    unit: 'balde 20L',
    weight: 23,
    image: '/products/lecatex-enduido-ext-20.jpg',
    images: '[]',
    category: 'Enduidos y Preparación',
    categorySlug: 'enduidos',
    featured: false,
    inStock: true,
    stockQty: 45,
    colors: '["Blanco","Gris"]',
    sizes: '["10L","20L"]',
  },
  {
    id: 'prod-lecatex-fijador-10',
    name: 'Lecatex Fijador Sellador 10L',
    slug: 'lecatex-fijador-sellador-10l',
    description: 'Fijador sellador de superficies que garantiza la adherencia del revestimiento o pintura. Impermeabiliza y uniformiza la absorción de la superficie.',
    price: 15900,
    comparePrice: null,
    unit: 'balde 10L',
    weight: 10,
    image: '/products/lecatex-fijador-10.jpg',
    images: '[]',
    category: 'Enduidos y Preparación',
    categorySlug: 'enduidos',
    featured: false,
    inStock: true,
    stockQty: 85,
    colors: '["Transparente","Blanco"]',
    sizes: '["4L","10L"]',
  },
  // Pinturas
  {
    id: 'prod-lecatex-latex-20',
    name: 'Lecatex Látex Satinado 20L',
    slug: 'lecatex-latex-satinado-20l',
    description: 'Pintura látex satinada de alta calidad para interiores. Acabado suave y lavable con excelente cobertura. Amplia paleta de colores disponible. Bajo olor y secado rápido.',
    price: 35900,
    comparePrice: 40000,
    unit: 'balde 20L',
    weight: 21,
    image: '/products/lecatex-latex-20.jpg',
    images: '[]',
    category: 'Pinturas',
    categorySlug: 'pinturas',
    featured: true,
    inStock: true,
    stockQty: 65,
    colors: '["Blanco","Beige","Gris","Celeste","Rosa","Verde salvia"]',
    sizes: '["4L","10L","20L"]',
  },
  {
    id: 'prod-lecatex-esmalte-4',
    name: 'Lecatex Esmalte Sintético 4L',
    slug: 'lecatex-esmalte-sintetico-4l',
    description: 'Esmalte sintético de alto brillo para madera y metal. Resistente al exterior y de acabado impecable. Excelente nivelación y cubritura.',
    price: 18900,
    comparePrice: null,
    unit: 'lata 4L',
    weight: 5,
    image: '/products/lecatex-esmalte-4.jpg',
    images: '[]',
    category: 'Pinturas',
    categorySlug: 'pinturas',
    featured: false,
    inStock: true,
    stockQty: 40,
    colors: '["Blanco","Negro","Rojo","Verde","Azul","Marrón"]',
    sizes: '["1L","4L"]',
  },
  // Accesorios
  {
    id: 'prod-rodillo-revestimiento',
    name: 'Rodillo para Revestimiento 23cm',
    slug: 'rodillo-revestimiento-23cm',
    description: 'Rodillo profesional de 23cm para aplicación de revestimientos plásticos y texturados. Mango antideslizante y refuerzo de alambre para mayor durabilidad.',
    price: 8900,
    comparePrice: null,
    unit: 'unidad',
    weight: 0.5,
    image: '/products/rodillo.jpg',
    images: '[]',
    category: 'Accesorios y Herramientas',
    categorySlug: 'accesorios',
    featured: false,
    inStock: true,
    stockQty: 200,
    colors: '[]',
    sizes: '[]',
  },
  {
    id: 'prod-espatula-acero',
    name: 'Espátula de Acero 30cm',
    slug: 'espatula-acero-30cm',
    description: 'Espátula de acero inoxidable de 30cm ideal para aplicación de revestimientos y enduidos. Mango ergonómico de madera. Borde recto para acabados prolijos.',
    price: 6500,
    comparePrice: null,
    unit: 'unidad',
    weight: 0.3,
    image: '/products/espatula.jpg',
    images: '[]',
    category: 'Accesorios y Herramientas',
    categorySlug: 'accesorios',
    featured: false,
    inStock: true,
    stockQty: 150,
    colors: '[]',
    sizes: '[]',
  },
  {
    id: 'prod-bandeja-pintura',
    name: 'Bandeja para Pintura con Rejilla',
    slug: 'bandeja-pintura-rejilla',
    description: 'Bandeja plástica de alta resistencia con rejilla escurridora incluida. Capacidad de 5L. Fácil de limpiar y reutilizable.',
    price: 4500,
    comparePrice: null,
    unit: 'unidad',
    weight: 0.4,
    image: '/products/bandeja.jpg',
    images: '[]',
    category: 'Accesorios y Herramientas',
    categorySlug: 'accesorios',
    featured: false,
    inStock: true,
    stockQty: 180,
    colors: '[]',
    sizes: '[]',
  },
];

const shippingRules = [
  {
    id: 'ship-caba',
    name: 'Envío CABA',
    type: 'standard',
    province: 'CABA',
    minAmount: 0,
    cost: 3500,
    freeAbove: 50000,
    active: true,
  },
  {
    id: 'ship-gba',
    name: 'Envío GBA',
    type: 'standard',
    province: 'Buenos Aires',
    minAmount: 0,
    cost: 5500,
    freeAbove: 70000,
    active: true,
  },
  {
    id: 'ship-interior',
    name: 'Envío Interior',
    type: 'standard',
    province: null,
    minAmount: 0,
    cost: 8500,
    freeAbove: 100000,
    active: true,
  },
  {
    id: 'ship-express-caba',
    name: 'Envío Express CABA',
    type: 'express',
    province: 'CABA',
    minAmount: 0,
    cost: 6500,
    freeAbove: 80000,
    active: true,
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.shippingRule.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Create categories
  for (const cat of categories) {
    await prisma.category.create({ data: cat });
  }
  console.log('Categories created');

  // Create products
  for (const prod of products) {
    await prisma.product.create({ data: prod });
  }
  console.log('Products created');

  // Create shipping rules
  for (const rule of shippingRules) {
    await prisma.shippingRule.create({ data: rule });
  }
  console.log('Shipping rules created');

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
